global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'doctrine-demo'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: doctrine-demo
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        action: keep
        regex: "8080"
      - source_labels: [__meta_kubernetes_pod_ip]
        target_label: __address__
        replacement: $1:8080
rule_files:
  - /etc/prometheus/prometheus.rules.yml
