apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctrine-z-api
  namespace: doctrine-z-lab
  labels:
    app: doctrine-z-api
    app.kubernetes.io/name: doctrine-z-api
    app.kubernetes.io/part-of: doctrine-z-ai-delivery-k8s-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doctrine-z-api
  template:
    metadata:
      labels:
        app: doctrine-z-api
        app.kubernetes.io/name: doctrine-z-api
        app.kubernetes.io/part-of: doctrine-z-ai-delivery-k8s-lab
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: doctrine-z-api
          image: doctrine-z-ai-delivery-k8s-lab:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: doctrine-z-api-config
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL
