apiVersion: v1
kind: Service
metadata:
  name: doctrine-z-api
  namespace: doctrine-z-lab
  labels:
    app: doctrine-z-api
    app.kubernetes.io/name: doctrine-z-api
    app.kubernetes.io/part-of: doctrine-z-ai-delivery-k8s-lab
spec:
  type: ClusterIP
  selector:
    app: doctrine-z-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
