apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - patch-resources.yaml
images:
  - name: doctrine-z-ai-delivery-k8s-lab
    newName: ghcr.io/flobehejohn/doctrine-z-ai-delivery-k8s-lab
    newTag: latest
