apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-prom
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://kpstack-kube-prometheus-st-prometheus.monitoring.svc:9090
        editable: false
